# Generated by Django 5.1.4 on 2025-01-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_default_creator(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    default_user = User.objects.first()  # Используем первого пользователя
    for post in Post.objects.all():
        post.creator = default_user
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
                null=True,  # Временно позволяем NULL, чтобы избежать ошибок
            ),
        ),
        migrations.RunPython(set_default_creator),  # Устанавливаем значения
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]